// ===== Gantt Chart — Activity Timeline =====

(function () {
  let ganttData = null;
  let isOpen = false;

  // ===== Build toggle button =====
  const filterBar = document.getElementById('filter-bar');
  if (!filterBar) return;

  const sep = document.createElement('div');
  sep.className = 'filter-sep';
  filterBar.appendChild(sep);

  const btn = document.createElement('button');
  btn.className = 'filter-btn';
  btn.id = 'gantt-toggle';
  btn.innerHTML = '<span class="dot gantt-dot"></span>Timeline';
  btn.addEventListener('click', toggleGantt);
  filterBar.appendChild(btn);

  // ===== Container =====
  const container = document.createElement('div');
  container.id = 'gantt-container';
  container.className = 'gantt-hidden';
  container.innerHTML = `
    <div class="gantt-header">
      <h2>Activity Timeline</h2>
      <div class="gantt-controls">
        <button class="gantt-src-btn active" data-src="all">All</button>
        <button class="gantt-src-btn" data-src="portfolio"><span style="color:#f472b6">&#9679;</span> Portfolio</button>
        <button class="gantt-src-btn" data-src="claude"><span style="color:#60a5fa">&#9679;</span> Claude</button>
        <span style="width:1px;height:18px;background:#1e1e2e;margin:0 6px"></span>
        <button class="gantt-zoom-btn" data-zoom="month">Month</button>
        <button class="gantt-zoom-btn active" data-zoom="week">Week</button>
        <button class="gantt-zoom-btn" data-zoom="day">Day</button>
        <button class="gantt-close" onclick="document.getElementById('gantt-toggle').click()">&times;</button>
      </div>
    </div>
    <div class="gantt-summary" id="gantt-summary"></div>
    <div class="gantt-chart-wrap">
      <svg id="gantt-chart"></svg>
    </div>
  `;
  document.body.appendChild(container);

  function toggleGantt() {
    isOpen = !isOpen;
    container.classList.toggle('gantt-hidden', !isOpen);
    btn.classList.toggle('active', isOpen);

    if (isOpen && !ganttData) {
      loadAndRender();
    }
  }

  // ===== Load data from history =====
  async function loadAndRender() {
    // Use remind-report for timeline data, or build from quiz/graph
    // We'll build the gantt from the inline data generated by sync
    try {
      const res = await fetch('./data/gantt-data.json');
      ganttData = await res.json();
    } catch {
      ganttData = generateFallbackData();
    }
    let currentZoom = 'week';
    let currentSrc = 'all';

    renderChart(currentZoom, currentSrc);
    renderSummary();

    // Zoom controls
    document.querySelectorAll('.gantt-zoom-btn').forEach(b => {
      b.addEventListener('click', () => {
        document.querySelectorAll('.gantt-zoom-btn').forEach(x => x.classList.remove('active'));
        b.classList.add('active');
        currentZoom = b.dataset.zoom;
        renderChart(currentZoom, currentSrc);
      });
    });

    // Source filter
    document.querySelectorAll('.gantt-src-btn').forEach(b => {
      b.addEventListener('click', () => {
        document.querySelectorAll('.gantt-src-btn').forEach(x => x.classList.remove('active'));
        b.classList.add('active');
        currentSrc = b.dataset.src;
        renderChart(currentZoom, currentSrc);
      });
    });
  }

  function generateFallbackData() {
    // Minimal fallback if gantt-data.json not available
    return { projects: [], dateRange: { start: '2026-02-09', end: '2026-06-29' } };
  }

  // ===== Summary =====
  function renderSummary() {
    const el = document.getElementById('gantt-summary');
    if (!ganttData.projects || ganttData.projects.length === 0) {
      el.innerHTML = '<span>No data</span>';
      return;
    }

    const totalDays = ganttData.projects.reduce((s, p) => s + p.activeDays, 0);
    const totalPrompts = ganttData.projects.reduce((s, p) => s + p.totalPrompts, 0);
    const months = new Set();
    ganttData.projects.forEach(p => {
      p.activity.forEach(a => months.add(a.date.slice(0, 7)));
    });

    el.innerHTML = `
      <span>${ganttData.projects.length} projects</span>
      <span>${totalPrompts.toLocaleString()} prompts</span>
      <span>${totalDays} active days</span>
      <span>${months.size} months</span>
      <span>${ganttData.dateRange.start} ~ ${ganttData.dateRange.end}</span>
    `;
  }

  // ===== Render Gantt Chart =====
  function renderChart(zoomLevel, srcFilter) {
    srcFilter = srcFilter || 'all';
    const svg = d3.select('#gantt-chart');
    svg.selectAll('*').remove();

    if (!ganttData.projects || ganttData.projects.length === 0) return;

    let projects = ganttData.projects.filter(p => p.totalPrompts >= 2 || p.source === 'portfolio');
    if (srcFilter !== 'all') {
      projects = projects.filter(p => p.source === srcFilter);
    }
    projects.sort((a, b) => a.startDate.localeCompare(b.startDate));

    const margin = { top: 40, right: 20, bottom: 30, left: 220 };
    const rowHeight = 28;
    const width = Math.max(800, container.clientWidth - 40);
    const height = margin.top + margin.bottom + projects.length * rowHeight;

    svg.attr('width', width).attr('height', height);

    // Date range
    const startDate = new Date(ganttData.dateRange.start);
    const endDate = new Date(ganttData.dateRange.end);
    endDate.setDate(endDate.getDate() + 1);

    // X scale
    const x = d3.scaleTime()
      .domain([startDate, endDate])
      .range([margin.left, width - margin.right]);

    // Y scale
    const y = d3.scaleBand()
      .domain(projects.map(p => p.name))
      .range([margin.top, height - margin.bottom])
      .padding(0.25);

    // ===== Grid lines =====
    const g = svg.append('g');

    // Time axis
    let tickFormat, ticks;
    if (zoomLevel === 'month') {
      ticks = d3.timeMonth.every(1);
      tickFormat = d3.timeFormat('%Y-%m');
    } else if (zoomLevel === 'week') {
      ticks = d3.timeWeek.every(1);
      tickFormat = d3.timeFormat('%m/%d');
    } else {
      ticks = d3.timeDay.every(1);
      tickFormat = d3.timeFormat('%d');
    }

    // X axis
    const xAxis = g.append('g')
      .attr('transform', `translate(0,${margin.top - 5})`)
      .call(d3.axisTop(x).ticks(ticks).tickFormat(tickFormat))
      .call(g => g.select('.domain').remove())
      .call(g => g.selectAll('.tick line').attr('stroke', '#1e1e2e'))
      .call(g => g.selectAll('.tick text').attr('fill', '#6b6b85').attr('font-size', '10px'));

    // Vertical grid
    g.append('g')
      .selectAll('line')
      .data(x.ticks(ticks))
      .join('line')
      .attr('x1', d => x(d)).attr('x2', d => x(d))
      .attr('y1', margin.top).attr('y2', height - margin.bottom)
      .attr('stroke', '#1e1e2e').attr('stroke-width', 0.5);

    // Month backgrounds (alternating)
    const months = d3.timeMonths(startDate, endDate);
    months.forEach((m, i) => {
      const nextMonth = new Date(m);
      nextMonth.setMonth(nextMonth.getMonth() + 1);
      if (i % 2 === 0) {
        g.append('rect')
          .attr('x', x(m))
          .attr('y', margin.top)
          .attr('width', Math.max(0, x(nextMonth) - x(m)))
          .attr('height', height - margin.top - margin.bottom)
          .attr('fill', 'rgba(255,255,255,0.015)');
      }
    });

    // ===== Project rows =====
    const rows = g.selectAll('.gantt-row')
      .data(projects)
      .join('g')
      .attr('class', 'gantt-row');

    // Row background (hover)
    rows.append('rect')
      .attr('x', 0).attr('y', d => y(d.name))
      .attr('width', width).attr('height', y.bandwidth())
      .attr('fill', 'transparent')
      .attr('class', 'gantt-row-bg');

    // Source indicator (portfolio vs claude)
    rows.append('circle')
      .attr('cx', 10)
      .attr('y', d => y(d.name))
      .attr('cy', d => y(d.name) + y.bandwidth() / 2)
      .attr('r', 3)
      .attr('fill', d => d.source === 'portfolio' ? '#f472b6' : '#60a5fa')
      .attr('opacity', 0.6)
      .append('title')
      .text(d => d.source === 'portfolio' ? 'Portfolio (실무)' : 'Claude (개발)');

    // Project labels
    rows.append('text')
      .attr('x', margin.left - 8)
      .attr('y', d => y(d.name) + y.bandwidth() / 2)
      .attr('text-anchor', 'end')
      .attr('dominant-baseline', 'central')
      .attr('fill', d => groupColor(d.group))
      .attr('font-size', '11px')
      .attr('font-weight', d => d.source === 'portfolio' ? '700' : '500')
      .attr('opacity', d => d.source === 'portfolio' ? 1 : 0.85)
      .text(d => d.name.length > 28 ? d.name.slice(0, 26) + '..' : d.name);

    // ===== Activity bars =====
    // Each project has daily activity data → draw bars
    rows.each(function (proj) {
      const row = d3.select(this);
      const barY = y(proj.name);
      const barH = y.bandwidth();

      // Continuous span bar (background)
      row.append('rect')
        .attr('x', x(new Date(proj.startDate)))
        .attr('y', barY)
        .attr('width', Math.max(2, x(new Date(proj.endDate)) - x(new Date(proj.startDate))))
        .attr('height', barH)
        .attr('rx', 3)
        .attr('fill', groupColor(proj.group))
        .attr('opacity', 0.08);

      // Individual day dots/bars
      proj.activity.forEach(day => {
        const date = new Date(day.date);
        const intensity = Math.min(1, day.count / 30);
        const barWidth = zoomLevel === 'day' ? Math.max(2, (width - margin.left - margin.right) / 150) :
                         zoomLevel === 'week' ? Math.max(3, (width - margin.left - margin.right) / 150 * 1.5) :
                         Math.max(4, (width - margin.left - margin.right) / 150 * 3);

        // Milestone diamond (portfolio projects with labels)
        if (day.label) {
          const cx = x(date), cy = barY + barH / 2;
          row.append('path')
            .attr('d', `M${cx},${cy - 6} L${cx + 5},${cy} L${cx},${cy + 6} L${cx - 5},${cy} Z`)
            .attr('fill', groupColor(proj.group))
            .attr('stroke', '#0a0a0f')
            .attr('stroke-width', 1)
            .attr('opacity', 0.9)
            .append('title')
            .text(`${day.date}: ${day.label}`);
        } else {
          row.append('rect')
            .attr('x', x(date) - barWidth / 2)
            .attr('y', barY + barH * 0.1)
            .attr('width', barWidth)
            .attr('height', barH * 0.8)
            .attr('rx', 2)
            .attr('fill', groupColor(proj.group))
            .attr('opacity', 0.2 + intensity * 0.7)
            .append('title')
            .text(`${day.date}: ${day.count} prompts`);
        }
      });
    });

    // ===== Today marker =====
    const today = new Date();
    if (today >= startDate && today <= endDate) {
      g.append('line')
        .attr('x1', x(today)).attr('x2', x(today))
        .attr('y1', margin.top - 5).attr('y2', height - margin.bottom)
        .attr('stroke', '#ef4444')
        .attr('stroke-width', 1.5)
        .attr('stroke-dasharray', '4 3');

      g.append('text')
        .attr('x', x(today))
        .attr('y', margin.top - 10)
        .attr('text-anchor', 'middle')
        .attr('fill', '#ef4444')
        .attr('font-size', '9px')
        .attr('font-weight', '700')
        .text('TODAY');
    }
  }

  function groupColor(group) {
    const colors = {
      dev: '#60a5fa',
      design: '#f472b6',
      publishing: '#34d399',
      planning: '#fbbf24',
      core: '#ffffff',
    };
    return colors[group] || '#60a5fa';
  }
})();
